[package]
name = "NFTMarketplace"
version = "0.1.0"

[addresses]
NFTMarketplace = "0xe930eba5471cc23bb7bd05ec9913449322c7362a0e71988d3d9117bd3a5a2c03"
aptos_framework = "0x1"
primitives = "0xCAFE"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }